### ISSUE TITLE
Literature: Nagy

### ISSUE THREAD

**Issue by benjyz** [NakamotoInstitute/nakamotoinstitute.org#118]
http://www.epointsystem.org/~nagydani/ICETE2005.pdf

ON DIGITAL CASH-LIKE PAYMENT SYSTEMS, Daniel A. Nagy

Nagy was a frequent contributor on Nick Szabo's blog, so this article might be worth listing.

See: http://www.metzdowd.com/pipermail/cryptography/2005-October/009820.html

**Comment by bitstein** [comment]
Great find. Added.
