### ISSUE TITLE
Lack of HTTPS/SSL

### ISSUE THREAD

**Issue by torkelrogstad** [NakamotoInstitute/nakamotoinstitute.org#177]
Currently, SNI runs on HTTP, without support for encrypted connections. Are there any plans to implement this? It can be done for free and very easily with Let's Encrypt.

**Comment by bitstein** [comment]
I am working on a new server deployment, and will be including HTTPS support as part of that process.

Thanks for bringing this up!

**Comment by bitstein** [comment]
Everything should be live and working. Closing, but let me know if you spot any problems.
