### ISSUE TITLE
Translation of Nick Szabo's Shelling Out

### ISSUE THREAD

**Issue by nelruk** [NakamotoInstitute/nakamotoinstitute.org#187]
Hello, I made a translation of Nick Szabo's _Shelling Out_ in markdown. Is there a section where I can leave the document?

I read the how-to-help section but actually I just want to deliver the document. I can't find a section that allow me to pull the document.

**Comment by bitstein** [comment]
Awesome! You can email it to me at michael (at) bitstein (dot) org

**Comment by nelruk** [comment]
E-mail sent.
