### ISSUE TITLE
Generate new addresses link returns a 404 status

### ISSUE THREAD

**Issue by prahaladbelavadi** [NakamotoInstitute/nakamotoinstitute.org#202]
The Generate new address link on the readme.md file points to https://pacio.li/bitcoind/2014/10/31/how-to-connect-to-bitcoin-cores-json-rpc-api-with-python.html which returns a 404 status.

It also uses a SSL certificate from Rochard.org @PierreRochard which was flagged by the browser.

**Comment by bitstein** [comment]
Thanks. This is a deprecated feature and a soon-to-be-merged branch will be removing it, so I am closing this issue. I appreciate you pointing this out!

**Comment by prahaladbelavadi** [comment]
Happy to help 👍
