### ISSUE TITLE
The first version of Bitcoin source code is missing a file

### ISSUE THREAD

**Issue by serhack** [NakamotoInstitute/nakamotoinstitute.org#246]
Hi, thanks for your work here! I do really appreciate Nakamoto Institute for collecting all the stuff about Satoshi. While studying the first version of Bitcoin source code (`bitcoin-nov08.tgz`) I noticed that a file is missing from the original BitcoinTalk thread. The file is [`node.h`](https://bitcointalk.org/index.php?topic=382374.msg4108783#msg4108783) and contains some nice details about the node that I'm sure the readers of nakamotoinstitute would not miss.

Note that I might be wrong.

**Comment by bitstein** [comment]
Thank you so much for catching this oversight! I've updated the tgz file and hashes accordingly. Please feel free to open another issue if I managed to mess it up again.

**Comment by serhack** [comment]
Great! You might want to get rid off all the metadata files generated by Apple.
