### ISSUE TITLE
Error when reading certain emails on website

### ISSUE THREAD

**Issue by sogoagain** [NakamotoInstitute/nakamotoinstitute.org#271]
I have encountered a bug on website where attempting to read certain emails results in an error page with the following message:

```
Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 1323241457
```

The error occurs when trying to access the following emails:

- "Bitcoin v0.1 released" (Jan 8, 2009, 19:27:40 UTC)
- "[bitcoin-list] Alert: upgrade to bitcoin 0.3.6" (Jul 30, 2010, 06:02:38 UTC)

This is my guess, but after some debugging, it appears that the error is occurring during the validation process of the `source` field in the `EmailBaseModel` class when creating the response object:

```python
source: str = Field(validation_alias=AliasPath("thread", "source"))
```

Thank you!

**Comment by bitstein** [comment]
Thanks, I saw a similar bug recently due to how I was doing the joined loads on the database. I will investigate.

**Comment by sogoagain** [comment]
@bitstein Thank you for the quick fix! I've confirmed that the pages are now working as expected. The issue seems to be resolved.
