### ISSUE TITLE
HTML entity is not being evaluated

### ISSUE THREAD

**Issue by luisschwab** [NakamotoInstitute/nakamotoinstitute.org#304]
On [The Quotable Satoshi](https://satoshi.nakamotoinstitute.org/quotes/), the HTML entity `&lsquo;` is not being evaluated and is instead being printed literally:

![Screenshot from 2024-06-21 13-50-21](https://github.com/NakamotoInstitute/nakamotoinstitute.org/assets/97608688/cf2e1eaa-458a-44b5-86a5-7eca7bca3b88)

**Comment by bitstein** [comment]
Fixed by f398b2eb1c86fc6113c8a053901f8c208671077c
